(function(root){'use strict';
const fields=[['task','Business task'],['unit','Accepted output unit'],['protocol','Common evaluation protocol / test-set reference'],['load','Test load and period'],['constraints','Data, safety, continuity and license requirements'],['owner','Decision owner'],['date','Review date','date'],['quality','Minimum acceptance rate (%)','number'],['latency','Maximum end-to-end p95 latency (ms)','number'],['cost','Maximum full cost per accepted unit (USD)','number']];
const checks=['Unknown','Meets stated requirement','Does not meet'];
const itemFields=[['name','Candidate configuration'],['model','Model and version'],['hosting','Hosting and operator'],['protocol','Evaluation protocol reference (must match scope)'],['quality','Measured acceptance rate (%)','number'],['latency','Measured end-to-end p95 latency (ms)','number'],['cost','Measured full cost per accepted unit (USD)','number'],['data','Data / jurisdiction requirement','select',checks],['safety','Safety and human-authority requirement','select',checks],['continuity','Continuity / recovery requirement','select',checks],['license','License / use-right requirement','select',checks],['evidence','Test report and control-evidence references'],['checked','Evidence review date','date'],['action','Next test or decision'],['actionOwner','Action owner'],['due','Action due date','date']];
const txt=ds=>Object.fromEntries(ds.map(f=>[f[0],f[2]==='select'?'Unknown':'']));
const item=()=>txt(itemFields);const blank=()=>({schema:'placement-test',version:1,example:false,scope:txt(fields),items:[item(),item()]});
const number=(v,max=Infinity)=>typeof v==='string'&&v.trim()!==''&&Number.isFinite(Number(v))&&Number(v)>=0&&Number(v)<=max?Number(v):null;
const date=v=>/^\d{4}-\d{2}-\d{2}$/.test(v)&&!isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v;
function validate(raw){if(!raw||raw.schema!=='placement-test'||raw.version!==1||typeof raw.example!=='boolean'||!raw.scope||!Array.isArray(raw.items)||raw.items.length<1||raw.items.length>6)throw Error('Expected a version 1 placement review with 1–6 candidates.');const d=blank();d.example=raw.example;
function copy(from,defs){const out={};for(const [key,,type,opts]of defs){const v=from?.[key];if(typeof v!=='string'||v.length>3000)throw Error('Invalid field: '+key);if(type==='select'&&!opts.includes(v))throw Error('Invalid option: '+key);if(type==='date'&&v&&!date(v))throw Error('Invalid date: '+key);out[key]=v;}return out;}
d.scope=copy(raw.scope,fields);d.items=raw.items.map(x=>copy(x,itemFields));return d;}
function evaluate(d){const s=d.scope,warnings=[];for(const [k,l]of fields)if(!s[k].trim())warnings.push('Supply '+l.toLowerCase()+'.');if(s.date&&!date(s.date))warnings.push('Use a valid review date.');for(const k of ['quality','latency','cost'])if(number(s[k],k==='quality'?100:Infinity)===null)warnings.push('Set a valid '+k+' threshold; blank is unknown.');
const cards=d.items.map((c,i)=>{const gaps=[],fails=[];for(const k of ['name','model','hosting','evidence','checked'])if(!c[k].trim())gaps.push('Missing '+k+'.');if(c.checked&&!date(c.checked))gaps.push('Invalid evidence date.');if(date(c.checked)&&date(s.date)&&c.checked>s.date)gaps.push('Evidence date is after the review date.');if(!c.protocol||!s.protocol||c.protocol!==s.protocol)gaps.push('Evaluation protocol is absent or does not match the common protocol.');
for(const k of ['quality','latency','cost']){const x=number(c[k],k==='quality'?100:Infinity),limit=number(s[k],k==='quality'?100:Infinity);if(x===null)gaps.push('Missing or invalid measured '+k+'.');else if(limit!==null&&(k==='quality'?x<limit:x>limit))fails.push(k+' misses the supplied threshold.');}
for(const k of ['data','safety','continuity','license'])if(c[k]==='Does not meet')fails.push(k+' requirement is not met.');else if(c[k]!=='Meets stated requirement')gaps.push(k+' requirement needs evidence review.');
const detail=[...fails,...gaps];if(warnings.length)detail.push('Complete the common scope before treating a comparison as usable.');return {title:c.name||'Candidate '+(i+1),verdict:fails.length?'Does not meet supplied requirements':gaps.length||warnings.length?'Evidence incomplete':'Within supplied thresholds — human review required',detail,action:c.action||'Define the next test.',owner:c.actionOwner||'Unassigned',due:c.due||'Unset'};});return {headline:'Compare the evidence. No automatic winner.',warnings,cards};}
function example(){const d=blank();d.example=true;Object.assign(d.scope,{task:'Internal maintenance-manual drafting assistant; no equipment control',unit:'Draft accepted by a qualified reviewer',protocol:'DEMO-TEST-01',load:'Illustrative fixed test set at the same concurrency; no measured customer results',constraints:'Approved US data path; human sign-off; tested queue fallback; permitted model use',owner:'Fictional service owner',date:'2026-09-24',quality:'95',latency:'2000',cost:'0.20'});d.items=[item(),item()];d.items.forEach((c,i)=>Object.assign(c,{name:i?'Premium candidate B':'Smaller-model candidate A',model:i?'Fictional model B v1':'Fictional model A v1',hosting:'Illustrative provider-run US environment',protocol:'DEMO-TEST-01',quality:i?'98':'96',latency:i?'1500':'1200',cost:i?'0.35':'0.12',data:checks[1],safety:checks[1],continuity:checks[1],license:checks[1],evidence:'DEMO-REPORT-'+(i+1)+'; all metrics and control assertions are teaching inputs',checked:'2026-09-24',action:i?'Test whether a higher budget has an evidenced benefit.':'Review representativeness and critical error classes before any deployment.',actionOwner:'Fictional evaluation owner',due:'2026-10-01'}));return d;}
const api={title:'What earns premium compute?',episode:'07',intro:'Compare candidate configurations against one workload’s acceptance criteria. Keep unknowns visible.',limit:6,fields,itemFields,blank,item,validate,evaluate,example,date,number,limitations:'This screens supplied evidence; it does not run evaluations, verify claims or authorize deployment. Aggregate acceptance rates can hide critical errors. Use the same task set, demand profile, cost scope and observation period. No vendor rankings or live prices are embedded.'};if(typeof module!=='undefined')module.exports=api;else root.ReviewModel=api;
})(globalThis);
