(function(root){'use strict';
const fields=[['service','Service / business promise'],['date','Schedule status date','date'],['terminal','Final service gate ID'],['owner','Schedule decision owner'],['assumptions','Scope, exclusions and estimate basis']];
const states=['Unknown','Open','Blocked','Accepted'];
const itemFields=[['id','Unique gate ID (letters, digits, hyphen)'],['name','Gate / remaining work'],['duration','Remaining calendar days (blank = unknown)','number'],['predecessors','Predecessor IDs, separated by commas'],['notBefore','Earliest start offset from status date, in calendar days','number'],['status','Gate status','select',states],['owner','Acceptance owner'],['evidence','Estimate / acceptance evidence reference'],['acceptedDate','Acceptance date (accepted gates only)','date'],['action','Next acceptance request or action'],['actionOwner','Action owner'],['due','Action due date','date']];
const txt=ds=>Object.fromEntries(ds.map(f=>[f[0],f[2]==='select'?'Unknown':'']));
const item=()=>txt(itemFields);const blank=()=>({schema:'delivery-gates',version:1,example:false,scope:txt(fields),items:[item()]});
const date=v=>/^\d{4}-\d{2}-\d{2}$/.test(v)&&!isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v;
const num=v=>typeof v==='string'&&v.trim()!==''&&Number.isInteger(Number(v))&&Number(v)>=0&&Number(v)<=36500?Number(v):null;
function validate(raw){if(!raw||raw.schema!=='delivery-gates'||raw.version!==1||typeof raw.example!=='boolean'||!raw.scope||!Array.isArray(raw.items)||raw.items.length<1||raw.items.length>20)throw Error('Expected a version 1 delivery review with 1–20 gates.');const d=blank();d.example=raw.example;function copy(from,defs){const out={};for(const[k,,t,o]of defs){const v=from?.[k];if(typeof v!=='string'||v.length>3000)throw Error('Invalid field: '+k);if(t==='select'&&!o.includes(v))throw Error('Invalid option: '+k);if(t==='date'&&v&&!date(v))throw Error('Invalid date: '+k);out[k]=v;}return out;}d.scope=copy(raw.scope,fields);d.items=raw.items.map(x=>copy(x,itemFields));return d;}
function evaluate(d){const warnings=[],errors=[],by=new Map(),pred=new Map(),order=[],active=new Set(),done=new Set(),s=d.scope;
for(const[k,l]of fields)if(!s[k].trim())errors.push('Supply '+l.toLowerCase()+'.');if(!date(s.date))errors.push('Use a valid schedule status date.');
for(const r of d.items){if(!/^[A-Za-z0-9-]+$/.test(r.id)||by.has(r.id))errors.push('Gate IDs must be valid and unique: '+(r.id||'[blank]'));by.set(r.id,r);if(!r.name||!r.owner||!r.evidence)errors.push((r.id||'Gate')+': supply name, owner and evidence reference.');if(num(r.duration)===null)errors.push(r.id+': remaining duration is unknown or invalid.');if(num(r.notBefore)===null)errors.push(r.id+': enter a valid earliest-start offset, including 0 if unrestricted.');if(r.status==='Unknown')errors.push(r.id+': status is unknown.');if(r.status==='Blocked')warnings.push(r.id+': blocked; the forecast assumes the entered estimate includes resolving the block.');if(r.status==='Accepted'&&(num(r.duration)!==0||num(r.notBefore)!==0||!date(r.acceptedDate)||r.acceptedDate>s.date))errors.push(r.id+': accepted requires zero remaining days/start offset and a valid acceptance date on or before status date.');if(r.status!=='Accepted'&&r.acceptedDate)errors.push(r.id+': acceptance date is present but status is not Accepted.');pred.set(r.id,[...new Set(r.predecessors.split(',').map(x=>x.trim()).filter(Boolean))]);}
if(!by.has(s.terminal))errors.push('Final service gate ID does not exist.');
for(const[id,ps]of pred)for(const p of ps){if(!by.has(p))errors.push(id+': predecessor '+p+' does not exist.');else if(by.get(id).status==='Accepted'&&by.get(p).status!=='Accepted')errors.push(id+': accepted gate has an unaccepted predecessor '+p+'.');}
function visit(id){if(active.has(id)){errors.push('Dependency cycle involving '+id+'.');return;}if(done.has(id)||!by.has(id))return;active.add(id);for(const p of pred.get(id)||[])visit(p);active.delete(id);done.add(id);order.push(id);}
for(const id of by.keys())visit(id);
const cards=d.items.map(r=>({title:r.id+' · '+r.name,verdict:'Not calculated',detail:[],action:r.action||'Confirm evidence and remaining work.',owner:r.actionOwner||r.owner||'Unassigned',due:r.due||'Unset'}));
if(errors.length)return{headline:'No forecast — resolve the missing or inconsistent inputs.',warnings:[...new Set([...errors,...warnings])],cards};
const included=new Set();function mark(id){if(included.has(id))return;included.add(id);pred.get(id).forEach(mark);}mark(s.terminal);
const es={},ef={},ls={},lf={},successors={};for(const id of included)successors[id]=[];
for(const id of order){if(!included.has(id))continue;const r=by.get(id);es[id]=Math.max(num(r.notBefore),0,...pred.get(id).map(p=>ef[p]));ef[id]=es[id]+num(r.duration);for(const p of pred.get(id))successors[p].push(id);}
const days=ef[s.terminal];for(const id of [...order].reverse()){if(!included.has(id))continue;lf[id]=id===s.terminal?days:Math.min(...successors[id].map(x=>ls[x]));ls[id]=lf[id]-num(by.get(id).duration);}
const stamp=n=>new Date(Date.parse(s.date+'T00:00:00Z')+n*86400000).toISOString().slice(0,10);
cards.forEach((c,i)=>{const r=d.items[i],id=r.id;if(!included.has(id)){c.verdict='Excluded from selected service path';c.detail=['Connect this gate if the service actually depends on it.'];warnings.push(id+': disconnected from the selected service gate; excluded from the forecast.');return;}const slack=ls[id]-es[id];c.verdict=r.status==='Accepted'?'Accepted — user-supplied record':slack===0?'Zero float — controls the modeled service path':'Has '+slack+' calendar days of modeled float';c.detail=['Earliest remaining start: '+stamp(es[id])+' (day '+es[id]+').','Earliest finish: '+stamp(ef[id])+' (day '+ef[id]+').','Total float: '+slack+' calendar days.'];});
warnings.unshift('Conditional calculation only: finish-to-start links, no lags, calendar days, no resource leveling or uncertainty analysis. No permit, energization or service approval is inferred.');
return{headline:'Modeled service finish: '+stamp(days)+' · '+days+' remaining calendar days',warnings,cards,days,es,ef,ls,lf};}
function example(){const d=blank();d.example=true;Object.assign(d.scope,{service:'Fictional regional AI service environment',date:'2026-09-24',terminal:'service',owner:'Fictional program sponsor',assumptions:'Teaching network only. Finish-to-start, calendar days, no lags or shared-resource limits. Each estimate is invented.'});d.items=[['shell','Shell accepted','0','','Accepted'],['power','Energization acceptance','10','shell','Open'],['network','Network acceptance','3','shell','Open'],['commission','Integrated commissioning','4','power','Open'],['service','Operations acceptance','2','commission,network','Open']].map(([id,name,duration,predecessors,status])=>({...item(),id,name,duration,predecessors,status,notBefore:'0',owner:'Fictional '+id+' owner',evidence:'DEMO-'+id+'; invented estimate / record',acceptedDate:status==='Accepted'?'2026-09-23':'',action:'Confirm exit evidence and dependency assumptions.',actionOwner:'Fictional program manager',due:'2026-09-25'}));return d;}
const api={title:'What moves the service date?',episode:'08',intro:'Connect remaining work and acceptance evidence. Identify zero-float work under an explicit, simplified schedule model.',limit:20,fields,itemFields,blank,item,validate,evaluate,example,limitations:'This is a teaching and review aid, not an engineering schedule or readiness approval. It calculates only the selected terminal gate and its ancestors. All inputs are user assertions. It omits resource limits, working calendars, probabilistic delays, start-to-start links and contractual interpretation. A critical path can change when inputs change.'};if(typeof module!=='undefined')module.exports=api;else root.ReviewModel=api;
})(globalThis);
